name: publish

on:
  push:
    tags: [ "v[0-9]+.[0-9]+.[0-9]+" ]

jobs:

  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
          registry-url: "https://registry.npmjs.org"

      - run: npm ci
      - run: npm run build
      - run: npm test

      - uses: actions/upload-artifact@v4
        with:
          name: build-${{ github.ref_name }}
          path: build

      - name: Publish extension
        run: |
          zip --recurse-paths ../build.zip .
          unzip -l ../build.zip
          npx --yes chrome-webstore-upload-cli@3.3.0 --source ../build.zip
        working-directory: build
        env:
          EXTENSION_ID: ${{ vars.EXTENSION_ID }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}

      - name: Create release draft
        run: gh release create ${{ github.ref_name }} --generate-notes --draft
        env:
          GH_TOKEN: ${{ github.token }}
